### ISSUE TITLE
Doesn't always fully resolve

### ISSUE THREAD

**Issue by iangilman** [KTGLeiden/Openseadragon-screenshot#1] opened 2016-10-10 19:01 UTC
I just tried the demo, and the image it produced didn't have all of the high res tiles loaded (it was blurry in some portions).

**Comment by KTGLeiden** [comment] 2016-10-11 07:51
Okay, that's weird. I do think it is correctly attached to the fully-loaded event. What might be the issue is that there was still an animation going on while you made the screenshot? I have not been able to rule all user movement out yet.

**Comment by iangilman** [comment] 2016-10-12 16:44
I'm pretty sure I didn't interact any more than just hitting the snapshot button and hitting okay on the default options. I'm on mac firefox. Here's the image it produced:

![screenshot 1](https://cloud.githubusercontent.com/assets/338989/19319064/011b9f66-9060-11e6-8ed6-39da2ac5f3f9.png)

You can see it's unresolved on the right.

**Comment by enver315** [comment] 2017-03-08 11:12
Hello 
I just tried to make screenshot with openseadragon screenshot plugin.but when i clicked the button it returns me -->Loading image... 
Takes too long?
Refresh page. i could not understand what i ve missed.

**Comment by KTGLeiden** [comment] 2017-03-08 11:44
Hi there,

That is only a little wait message with which I am trying to make clear that you have to wait for some time. Please try the option "Just take a screenshot", which will give you a screenshot of your current viewport size.
If this does not work, please let me know which browser you are using.
As for Ian: 
Still have no clue on this. I will fix this if there is a release with the fully-loaded event.

**Comment by enver315** [comment] 2017-03-08 12:37
Hi there

Thank you for your quick reply.I've tried "just take a screenshot" but
still same message occurs.And i am using chrome.Below ,you can see my tiny
code.Maybe i am doing something wrong.

var viewer = OpenSeadragon({

id: "openseadragon1",
prefixUrl: "openseadragon/images/",
tileSources: "openseadragon/dzc_output.xml",
 crossOriginPolicy: "Anonymous",
});

viewer.zoomPerClick = 1
if(viewer.initializeAnnotations()){
viewer.areAnnotationsActive();
viewer.annotations.get();
}
else
{
alert('error');
}
viewer.screenshot({
        showOptions: true, // Default is false
        keyboardShortcut: 'p', // Default is null
       showScreenshotControl: true // Default is true

    });

2017-03-08 14:44 GMT+03:00 KTGLeiden <notifications@github.com>:

**Comment by iangilman** [comment] 2017-03-08 17:40
@KTGLeiden Yes, sorry for the delay on releasing the new version with the fully-loaded event! Here's the tracking issue: 

https://github.com/openseadragon/openseadragon/issues/1094

My biggest concern is this one:

https://github.com/openseadragon/openseadragon/issues/1020

Anyway, it hasn't been forgotten...

**Comment by KTGLeiden** [comment] 2020-06-01 15:10
@iangilman Coming back to this 3 years later (:p) I think the issue is resolved. Just ran a quick test and received a very clean image.
I am going to close this issue for now, since I cannot reproduce it.

Thanks!

**Closed by KTGLeiden** 2020-06-01 15:10 UTC

**Comment by iangilman** [comment] 2020-06-02 17:29
Awesome… Better late than never :-)
